spring:
  application:
    name: picpay-simplificado
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay-simplificado
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          enable: true
          required: true
