spring:
  application:
    name: juno
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay-simplificado
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
